routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

Route::middleware('MultiLanguage')->group(function () {
    Route::get('/',[HomeController::class, 'index'])->name('home');
    Route::get('/change-language/{lang}',[HomeController::class, 'changeLang'])->name('changeLang');
});
Route::get('/honors',[HomeController::class, 'honors'])->name('honors');
Route::get('/category/{slug}/',[ProductController::class, 'showCategory'])->name('showCategory');
Route::get('/subsetCompany/{slug}',[HomeController::class, 'subsetCompany'])->name('showSubsetCompany');
Route::get('/products',[HomeController::class, 'products'])->name('products');
Route::get('/products/{slug}',[HomeController::class, 'showProduct'])->name('showProduct');
Route::get('/services/{slug}',[HomeController::class, 'showService'])->name('showService');
Route::get('/services',[HomeController::class, 'services'])->name('services');
Route::get('/catalog',[ProductController::class, 'show'])->name('catalog');
Route::get('/blog',[BlogController::class, 'blog'])->name('blog');
Route::get('/blog/search/',[BlogController::class, 'blogSearch'])->name('blog.search');
Route::get('/blog/category/{slug}',[BlogController::class, 'blogCategory'])->name('blog.category');
Route::get('/blog/post/{slug}',[BlogController::class, 'show'])->name('blog.post');
Route::get('/faq',[HomeController::class, 'faq'])->name('faq');
Route::get('/about',[HomeController::class, 'about'])->name('about');
Route::get('/contact',[HomeController::class, 'contact'])->name('contact.show');
Route::post('/sendMessage',[HomeController::class, 'sendMessage'])->name('contact.sendMessage');
Route::post('/sendGetAdvice',[HomeController::class, 'sendGetAdvice'])->name('contact.sendGetAdvice');
Route::post('/search',[HomeController::class, 'search'])->name('front_search');

Auth::routes();
Route::get('/password/forget/mobile', [App\Http\Controllers\Auth\ForgotPasswordController::class,'sendVerifyCode'])->name('auth.sendVerifyCode');
Route::post('/password/mobile/verify', [App\Http\Controllers\Auth\ForgotPasswordController::class,'showNewPassword'])->name('auth.showNewPassword');
Route::post('/password/new', [App\Http\Controllers\Auth\ForgotPasswordController::class,'newPassword'])->name('auth.newPassword');
Route::get('/login/loginWithVerifyCode', [App\Http\Controllers\AuthController::class,'loginWithVerifyCode'])->name('auth.loginWithVerifyCode');
Route::get('/login-register', [App\Http\Controllers\AuthController::class,'loginRegister'])->name('auth.loginRegister');
Route::post('/login-register', [App\Http\Controllers\AuthController::class,'doLoginRegister'])->name('auth.doLoginRegister');



Route::middleware('auth')->group(function (){
    Route::get('/profile',                         [App\Http\Controllers\UserController::class,    'showProfile'])->name('profile.showProfile');
    Route::get('/profile/personal-info',            [App\Http\Controllers\UserController::class,    'personalInfo'])->name('profile.personalInfo.show');
    Route::post('/profile/personal-info',           [App\Http\Controllers\UserController::class,    'update'])->name('profile.personalInfo.update');
    Route::post('/profile/verifyMobile',            [App\Http\Controllers\UserController::class,    'verifyMobile'])->name('profile.verifyMobile');
    Route::post('/profile/updateMobile',            [App\Http\Controllers\UserController::class,    'updateMobile'])->name('profile.updateMobile');
    Route::get('/user',                             [App\Http\Controllers\UserController::class,    'user'])->name('user.user');
});

app/Models/User.php
<?php

namespace App\Models;

use App\Http\Requests\ProductComment\ProductComments;
use Hekmatinasser\Verta\Verta;
use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name','last_name','national_id','mobile','card_number', 'email', 'password','role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function getBirthdayAttribute($value){
        $birthday[0] = Verta::instance($value)->year;
        $birthday[1] = Verta::instance($value)->month;
        $birthday[2] = Verta::instance($value)->day;
        return $birthday;
    }

    public function setBirthdayAttribute($value)
    {
        $birthday = explode('-', $value);
        $birthday = Verta::getGregorian($birthday[0],$birthday[1],$birthday[2]);
        $this->attributes['birthday'] = $birthday[0].'-'.$birthday[1].'-'.$birthday[2];
    }
    public function getCreatedAtAttribute($value){
        return Verta::instance($value)->format('H:i:s Y/m/d ');
    }

    public function role(){
        return $this->belongsTo(Role::class);
    }

    public function cart(){
        return $this->hasOne(Cart::class);
    }

    public function address(){
        return $this->hasMany(UserAddress::class);
    }

    public function orders(){
        return $this->hasMany(Order::class);
    }

    public function posts(){
        return $this->hasMany(BlogPost::class);
    }

    public function productComments(){
        return $this->hasMany(ProductComment::class);
    }

    public function prices(){
        return $this->belongsToMany(PriceProduct::class,'price_product_users','price_product_user_id','price_product_id');
    }

    public function discounts(){
        return $this->belongsToMany(Discount::class);
    }

    public function discountUsedCount(){
        return $this->hasMany(DiscountUserUsedCount::class);
    }




}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Classes\PriceFilter;
use App\Classes\SendSMS;
use App\Filters\Front\ProductsFilter;
use App\Models\Banner;
use App\Models\BlogPost;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Discount;
use App\Models\Faq;
use App\Models\FaqCategory;
use App\Models\CommonImage;
use App\Models\Honor;
use App\Models\PriceProduct;
use App\Models\Product;
use App\Models\ProductProperty;
use App\Models\Service;
use App\Models\SubsetCompanies;
use Carbon\Carbon;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Response;
use Illuminate\View\View;
use Illuminate\Pagination\LengthAwarePaginator;

use phpDocumentor\Reflection\Types\Self_;
use stdClass;

class HomeController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $lang = app()->getLocale();
        $slides = Banner::with(['langs'=>function ($query)use ($lang){$query->where('lang_id',$lang);}])->where('position', 'slide')->where('published', 1)->get();
        $services = Service::with(['langs'=>function ($query)use ($lang){$query->where('lang_id',$lang);}])->where('published', 1)->get();
        $specialServices = $services->where('special', 1)->take(3);
        $specialProducts = Product::with(['langs'=>function ($query)use ($lang){$query->where('lang_id',$lang);},'images'])->where('published', 1)->where('special', 1)->take(4)->get();
        $banners = Banner::where('position', 'like', '%home%')->where('published', 1)->get();
        $blog = BlogPost::with('user')->currentLang($lang)->orderBy('created_at')->get();

        return view('home', compact(
            'blog',
            'slides',
            'specialProducts',
            'services',
            'specialServices',
            'banners'));
    }

    /**
     * Display a listing of the resource.
     *
     * @param $languageCode
     * @return RedirectResponse
     */
    public function changeLang($languageCode): RedirectResponse
    {
        App::setLocale($languageCode);
        session()->put("lang_code",$languageCode);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return Factory|View
     */
    public function contact()
    {
        return view('general.contact');
    }

    public function sendMessage(Request $request)
    {

        $validatedData = $request->validate([
            'name' => 'bail|required|string|max:255',
            'subject' => 'bail|string',
            'phone' => 'bail|digits:11',
            'email' => 'bail|required|email',
            'message' => 'bail|required|max:9000',
        ]);

        try {

            $configs = getSiteConfigs();
            $to_name = 'مدیرسایت';
            $to_email = $configs->email;
            $data = array(
                'name' => $request->fullName,
                'subject' => $request->subject,
                'phone' => $request->phone,
                'email' => $request->email,
                'messages' => $request->message);

            Mail::send('email.email', $data, function ($message) use ($to_name, $to_email, $request) {
                $message->to($to_email, $to_name)->subject('ایمیل از فروشگاه');
                $message->from($request->email, 'پیام از سایت');
            });

            SendSMS::sendContact('رامین',$request->subject, $request->email, '09143012118', 'getMessage');

            return Response::json(array('status' => true), 200);
        } catch (\Exception $e) {
            return Response::json($e->getMessage(), 500);
        }
    }

    public function sendGetAdvice(Request $request)
    {

        $validatedData = $request->validate([
            'name' => 'bail|required|string|max:255',
            'phone' => 'bail|digits:11',
            'email' => 'bail|required|email',
        ]);

        try {

            SendSMS::sendContact('رامین',$request->name, $request->phone, $request->email, 'getAdvice');

            return Response::json(array('status' => true), 200);
        } catch (\Exception $e) {
            return Response::json($e->getMessage(), 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return Factory|View
     */
    public function faq()
    {
        $faqs = FaqCategory::with('faqs')->where('published', 1)->get();
        return view('general.faq', compact('faqs'));
    }

    public function about(){
        return view('general.about');
    }

    public function products(){

        $categories = Category::where('published', 1)->with(['langs'])->get();
        $products = Product::with([
            'langs'=>function ($query){$query->where('lang_id',app()->getLocale());},
            'images'=>function ($query){$query->where('is_main',1);}])->where('published', 1)->paginate(3);
        return view('product.products',compact('products','categories'));
    }

    public function showProduct($slug){
        $products = Product::with([
            'langs'=>function ($query){$query->where('lang_id',app()->getLocale());},
            'images'=>function ($query){$query->where('is_main',1);}])->where('published', 1)->take(4)->get();
        $product = Product::with([
            'langs'=>function ($query){$query->where('lang_id',app()->getLocale());},
            'images'=>function ($query){$query->where('is_main',1);}
        ])->where('published', 1)->where('slug',$slug)->first();
        return view('product.product',compact('product','products'));
    }

    public function services(){
        $services = Service::with(['langs'=>function ($query){$query->where('lang_id',app()->getLocale());}])->where('published', 1)->take(3)->get();
        return view('service.services',compact('services'));
    }

    public function showService($slug){
        $services = Service::with(['langs'=>function ($query){$query->where('lang_id',app()->getLocale());}])->where('published', 1)->get();
        $service = Service::with(['langs'=>function ($query){$query->where('lang_id',app()->getLocale());},'faqs'])->where('published', 1)->where('slug',$slug)->first();
        return view('service.service',compact('services','service'));
    }

    public function honors(){
        $honors = Honor::with(['langs'=>function ($query){$query->where('lang_id',app()->getLocale());}])->where('published', 1)->get();
        return view('general.honor',compact('honors'));
    }

    public function subsetCompany($slug){
        $subsetCompany = SubsetCompanies::with([
            'langs'=>function ($query){$query->where('lang_id',app()->getLocale());},
            'services.langs'=>function ($query){$query->where('lang_id',app()->getLocale());},
            'products.langs'=>function ($query){$query->where('lang_id',app()->getLocale());},
        ])->where('slug',$slug)->first();

        $services = $subsetCompany->services->count() > 0 ? $subsetCompany->services : null;
        $products = $subsetCompany->products->count() > 0 ? $subsetCompany->products : null;
        return view('subsetCompany.subsetCompany',compact('subsetCompany','services','products'));
    }

}

resources/views/component/home/about.blade.php
<section class="pt-0 overflow-visible {{'mt-'.$topMargin}}">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            @if($image)
                <div class="col-lg-6 mb-2-3 mb-lg-0">
                    <div class="position-relative pe-xl-1-9">
                        <img src="{{$image}}" class="border-radius-10" alt="دینامیک پایش">
                        <div
                            class="bg-secondary d-inline-block border-radius-10 p-1-9 position-absolute left-5 left-sm-n5 bottom-n5">
                            <p class="text-white mb-1">@lang('general.MoreThan')</p>
                            <h3 class="mb-0 h1 text-white">@lang('general.AdecadeOfExperience')</h3>
                        </div>
                    </div>
                </div>
            @endif
            <div class="col-lg-6">
                <div class="ps-xl-2-3 position-relative">
                    <span class="title-style02 text-secondary opacity06 position-absolute z-index-0 top-n10 ani-left-right alt-font">{{__('general.AboutUS')}}</span>
                    <div class="z-index-1 position-relative">
                        <h2 class="mb-lg-4 h2">{{$slogan}}</h2>
                        <p class="mb-1-9 text-justify">{{$about}}</p>
                        <div class="row align-items-center">
                            <div class="col-lg-6">
                                @if($services)
                                    @foreach($services as $service)
                                        @if($loop->iteration ^ 2 === 0)
                                            <div class="d-flex mb-1-9">
                                                <div class="flex-shrink-0">
                                                    <i class="ti-shopping-cart-full display-14 text-primary"></i>
                                                </div>
                                                <div class="flex-grow-1 {{app()->getLocale() === 'fa' ? ' ms-3' : ' me-3'}}">
                                                    <h4 class="h6">{{$service->langs[0]->title}}</h4>
                                                    <p class="mb-0">{{str_limit($service->langs[0]->title,25,'...')}}</p>
                                                </div>
                                            </div>
                                        @endif
                                    @endforeach
                                @endif
                            </div>
                            <div class="col-lg-6">
                                @if($services)
                                    @foreach($services as $service)
                                        @if($loop->iteration ^ 2 !== 0)
                                            <div class="d-flex mb-1-9">
                                                <div class="flex-shrink-0">
                                                    <i class="ti-shopping-cart-full display-14 text-primary"></i>
                                                </div>
                                                <div class="flex-grow-1 {{app()->getLocale() === 'fa' ? ' ms-3' : ' me-3'}}">
                                                    <h4 class="h6">{{$service->langs[0]->title}}</h4>
                                                    <p class="mb-0">{{str_limit($service->langs[0]->title,25,'...')}}</p>
                                                </div>
                                            </div>
                                        @endif
                                    @endforeach
                                @endif
                            </div>
                            {{--                                    <div class="col-lg-6">--}}
                            {{--                                        <div class="d-flex mb-1-9">--}}
                            {{--                                            <div class="flex-shrink-0">--}}
                            {{--                                                <i class="ti-direction-alt display-14 text-primary"></i>--}}
                            {{--                                            </div>--}}
                            {{--                                            <div class="flex-grow-1 {{app()->getLocale() === 'fa' ? ' ms-3' : ' me-3'}}">--}}
                            {{--                                                <h4 class="h6">راهبری تولید</h4>--}}
                            {{--                                                <p class="mb-0">-</p>--}}
                            {{--                                            </div>--}}
                            {{--                                        </div>--}}
                            {{--                                        <div class="d-flex mb-1-9">--}}
                            {{--                                            <div class="flex-shrink-0">--}}
                            {{--                                                <i class="ti-settings display-14 text-primary"></i>--}}
                            {{--                                            </div>--}}
                            {{--                                            <div class="flex-grow-1 {{app()->getLocale() === 'fa' ? ' ms-3' : ' me-3'}}">--}}
                            {{--                                                <h4 class="h6">ماشین سازی</h4>--}}
                            {{--                                                <p class="mb-0">-</p>--}}
                            {{--                                            </div>--}}
                            {{--                                        </div>--}}
                            {{--                                        <div class="d-flex">--}}
                            {{--                                            <div class="flex-shrink-0">--}}
                            {{--                                                <i class="ti-package display-14 text-primary"></i>--}}
                            {{--                                            </div>--}}
                            {{--                                            <div class="flex-grow-1 {{app()->getLocale() === 'fa' ? ' ms-3' : ' me-3'}}">--}}
                            {{--                                                <h4 class="h6">تامین کالا</h4>--}}
                            {{--                                                <p class="mb-0">-</p>--}}
                            {{--                                            </div>--}}
                            {{--                                        </div>--}}
                            {{--                                    </div>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/component/home/address.blade.php
<div class="overflow-visible">
    <div class="container">
        <div class="row footer-address">
            <div class="col-lg-3">
                <div class="bg-secondary p-1-9 border-radius-10 text-center h-100">
                    <img src="{{$logoAlternative}}" alt="{{$title}}">
                </div>
            </div>
            <div class="col-lg-9">
                <div class="bg-white p-1-9 shadow border-radius-10 position-relative">
                    <div class="row">
                        <div class="col-md-5 mb-3 mb-md-0">
                            <div class="d-flex align-items-center">
                                <div class="flex-shrink-0">
                                    <i class="ti-location-pin display-26 text-secondary"></i>
                                </div>
                                <div class="flex-grow-1 mx-3">
                                    @if(!empty($address))
                                        <p class="mb-0">{{$address}}</p>
                                    @endif
                                </div>
                            </div>
                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1 mx-3">
                                    @if(!empty($addressTwo))
                                        <p class="mb-0 ms-3">{{$addressTwo}}</p>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 mb-3 mb-md-0">
                            <div class="d-flex align-items-center">
                                <div class="flex-shrink-0">
                                    <i class="ti-mobile display-26 text-secondary"></i>
                                </div>
                                <div class="flex-grow-1 mx-3">
                                    @if(!empty($tel1))
                                        <p class="mb-0">
                                            <a href="tel:{{$tel1}}">{{$tel1}}</a>
                                        </p>
                                    @endif
                                    @if(!empty($tel2))
                                        <p class="mb-0">
                                            <a href="tel:{{$tel2}}">{{$tel2}}</a>
                                        </p>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="d-flex align-items-center">
                                <div class="flex-shrink-0">
                                    <i class="ti-email display-26 text-secondary"></i>
                                </div>
                                <div class="flex-grow-1 mx-3">
                                    @if(!empty($email))
                                        <p class="mb-0">
                                            <a href="mailto:{{$email}}">{{$email}}</a>
                                        <p class="mb-0">
                                    @endif
                                    @if(!empty($postalCode))
                                        <p>@lang('general.PostalCode'): {{$postalCode}}</p>
                                    @endif

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/component/home/blog.blade.php
<section class="pt-0 overflow-visible">
    <div class="container">
        <div class="bg-light-gray border-radius-10 p-1-6 p-sm-1-9 p-lg-10 position-relative">
            <div class="title-style03 text-center mb-2-3 mb-md-6">
                <h2 class="h1">{{__('general.OurLatestNews')}}</h2>
            </div>
            <div class="row mt-n1-9">
                @foreach($blog as $post)
                    <div class="col-md-6 col-lg-4 mt-1-9">
                        <div class="shadow border-radius-10">
                            <img src="{{$post->image_url}}" class="border-top-radius-10" alt="{{$post->langs[0]->title}}">
                            <div class="p-1-6 p-sm-1-9 bg-white border-radius-10">
                                <h3 class="mb-4 h5" style="min-height: 48px"><a href="{{route('blog.post',$post->slug)}}">{{\Illuminate\Support\Str::limit($post->langs[0]->title,58,$end=' ...')}}</a></h3>
                                <div class="d-flex align-items-center justify-content-between">
                                    <div>
                                        {{--                                <img src="img/avatar/avatar-09.jpg" class="w-30px rounded-circle" alt="...">--}}
                                        <span class="small text-primary font-weight-600 ms-1 ms-sm-2">{{$post->user->full_name}}</span>
                                    </div>
                                    <div class="d-flex">
                                        <i class="ti-calendar mx-1"></i>
                                        <span class="small font-weight-600">{{$post->created_at}}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
    <img src="{{env('App_Folder').'/img/shape/12.png'}}" class="position-absolute right-5 bottom-n5 ani-move d-none d-sm-block">
</section>

resources/views/component/home/client.blade.php
<section class="p-0 mx-md-9 mt-n6 bg-transparent" dir="ltr">
    <div class="container-fluid">
        <div class="bg-secondary px-4 px-sm-5 py-1-9 border-radius-10">
            <div class="owl-carousel owl-theme client-02">
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/01.png" alt="...">
                    <img class="main-image" src="img/partners/09.png" alt="...">
                </div>
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/02.png" alt="...">
                    <img class="main-image" src="img/partners/10.png" alt="...">
                </div>
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/03.png" alt="...">
                    <img class="main-image" src="img/partners/11.png" alt="...">
                </div>
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/04.png" alt="...">
                    <img class="main-image" src="img/partners/12.png" alt="...">
                </div>
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/05.png" alt="...">
                    <img class="main-image" src="img/partners/13.png" alt="...">
                </div>
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/06.png" alt="...">
                    <img class="main-image" src="img/partners/14.png" alt="...">
                </div>
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/07.png" alt="...">
                    <img class="main-image" src="img/partners/15.png" alt="...">
                </div>
                <div class="image-wrapper">
                    <img class="hover-image" src="img/partners/08.png" alt="...">
                    <img class="main-image" src="img/partners/16.png" alt="...">
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/component/home/homeSlider.blade.php
<section class="screen-height py-0 top-position1" dir="ltr">
    <div class="container-fluid px-0">
        <div class="slider-fade1 owl-carousel owl-theme w-100">
            @foreach($slides as $slide)
                <div class="item bg-img cover-background" data-overlay-dark="5"
                     data-background="{{$slide->image_url}}">
                    <div class="container h-100">
                        <div class="d-table w-100 h-100">
                            <div class="d-table-cell align-middle">
                                <div class="row align-items-center {{app()->getLocale() === 'fa' ? 'justify-content-end' : ''}}">
                                    <div class="col-md-10 col-lg-8 col-xl-7 col-xxl-6 z-index-3 position-relative">
                                        <h1 class="display-19 display-sm-13 display-md-9 display-lg-8 display-xl-4 text-white mb-3 {{app()->getLocale() === 'fa' ? 'text-start' : ''}}">
                                            {{$slide->langs[0]->title}}
                                        </h1>
                                        <p class="lead w-95 w-md-90 w-lg-85 mb-2-2 text-white opacity8 d-none d-sm-block {{app()->getLocale() === 'fa' ? 'text-start' : ''}}">
                                            {{$slide->description}}
                                        </p>
                                        @if($slide->url !== '#')
                                            <a href="{{$slide->url}}" class="butn-style3 white-hover me-2 my-1 my-sm-0">
                                                <span>@lang('general.ReadeMore')</span>
                                            </a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <img src="img/shape/11.png" class="position-absolute right-10 top-20 ani-top-bottom z-index-3">
    <img src="img/shape/10.png" class="position-absolute left-5 top-15 ani-move d-none d-xl-block z-index-3">
</section>